services:
  nifi:
    image: apache/nifi:2.4.0
    container_name: nifi-${KEY}
    ports:
      - "${NIFI_WEB_HTTPS_PORT}:${NIFI_WEB_HTTPS_PORT}" # Host HTTPS port -> container's port
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=${NIFI_USERNAME}
      - SINGLE_USER_CREDENTIALS_PASSWORD=${NIFI_PASSWORD}
      - NIFI_WEB_HTTPS_PORT=${NIFI_WEB_HTTPS_PORT}
      - NIFI_WEB_HTTPS_HOST=0.0.0.0
    volumes:
      - nifi_content:/opt/nifi/nifi-current/content_repository
      - nifi_flowfile:/opt/nifi/nifi-current/flowfile_repository
      - nifi_provenance:/opt/nifi/nifi-current/provenance_repository
      - nifi_conf:/opt/nifi/nifi-current/conf
      - ${MYSQL_CONNECTOR_PATH}:/opt/nifi/drivers/mysql-connector-j-9.3.0/mysql-connector-j-9.3.0.jar:ro
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql-${KEY}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-${KEY}
    restart: unless-stopped
    environment:
      PMA_HOST: mysql-${KEY}
      PMA_USER: ${MYSQL_ROOT_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
      - "${PHPMYADMIN_PORT}:80"

  nifi-backup:
    image: alpine
    container_name: nifi-backup-${KEY}
    depends_on:
      - nifi
    volumes:
      - nifi_content:/data/content_repository:ro
      - nifi_flowfile:/data/flowfile_repository:ro
      - nifi_provenance:/data/provenance_repository:ro
      - nifi_conf:/data/conf:ro
      - ./nifi_backup:/backup
    command: >
      sh -c "
        apk add --no-cache rsync &&
        while true; do
          echo '[nifi-backup] Running rsync backup at $(date)' &&
          rsync -av --delete /data/content_repository/ /backup/content_repository/ &&
          rsync -av --delete /data/flowfile_repository/ /backup/flowfile_repository/ &&
          rsync -av --delete /data/provenance_repository/ /backup/provenance_repository/ &&
          rsync -av --delete /data/conf/ /backup/conf/ &&
          echo '[nifi-backup] Backup completed at $(date)' &&
          sleep 86400;
        done
      "

volumes:
  nifi_content:
  nifi_flowfile:
  nifi_provenance:
  nifi_conf:
  mysql_data:
